# Generated by Django 4.2.2 on 2023-07-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlquilerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='cod',
            field=models.CharField(max_length=20),
        ),
    ]
