# Generated by Django 4.2.2 on 2023-08-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlquilerApp', '0003_alter_alquiler_cod_alter_alquiler_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='Autor',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='Descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
