# Generated by Django 4.2.2 on 2023-08-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlquilerApp', '0004_alquiler_autor_alquiler_descripcion_alquiler_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/Productos'),
        ),
    ]
