# Generated by Django 4.2.2 on 2023-07-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerea1', models.CharField(max_length=20)),
                ('precio1', models.FloatField()),
                ('aerea2', models.CharField(max_length=20)),
                ('precio2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Moda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moda1', models.CharField(max_length=20)),
                ('precio1', models.FloatField()),
                ('moda2', models.CharField(max_length=20)),
                ('precio2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod1', models.CharField(max_length=20)),
                ('precio1', models.FloatField()),
                ('prod2', models.CharField(max_length=20)),
                ('precio2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social1', models.CharField(max_length=20)),
                ('precio1', models.FloatField()),
                ('social2', models.CharField(max_length=20)),
                ('precio2', models.FloatField()),
            ],
        ),
    ]
