# Generated by Django 4.2.2 on 2023-07-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EstenopoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aerea',
            old_name='aerea1',
            new_name='aerea',
        ),
        migrations.RenameField(
            model_name='aerea',
            old_name='precio1',
            new_name='precioaerea',
        ),
        migrations.RenameField(
            model_name='moda',
            old_name='moda1',
            new_name='moda',
        ),
        migrations.RenameField(
            model_name='moda',
            old_name='precio1',
            new_name='preciomoda',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio1',
            new_name='precioprod',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='prod1',
            new_name='prod',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='precio1',
            new_name='preciosocial',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='social1',
            new_name='social',
        ),
        migrations.RemoveField(
            model_name='aerea',
            name='aerea2',
        ),
        migrations.RemoveField(
            model_name='aerea',
            name='precio2',
        ),
        migrations.RemoveField(
            model_name='moda',
            name='moda2',
        ),
        migrations.RemoveField(
            model_name='moda',
            name='precio2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='prod2',
        ),
        migrations.RemoveField(
            model_name='social',
            name='precio2',
        ),
        migrations.RemoveField(
            model_name='social',
            name='social2',
        ),
    ]
