# Generated by Django 4.2.2 on 2023-07-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstenopoApp', '0003_rename_aerea_aerea_nombre_aerea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerea',
            name='nombre_aerea',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moda',
            name='nombre_moda',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_prod',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='social',
            name='nombre_social',
            field=models.CharField(max_length=100),
        ),
    ]
