# Generated by Django 4.2.2 on 2023-08-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstenopoApp', '0006_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='moda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/moda'),
        ),
    ]
